language: python
python:
    - "3.4"
sudo: false
dist: trusty
before_install:
    - apt-get update -qq
    - apt-get install -qq python-opencv python3-pil python3-gi gir1.2-gladeui-2.0 gir1.2-gtk-3.0 python3-dev cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev python3-numpy libjpeg-dev libpng-dev libtiff-dev xvfb
cache:
    directories:
        - $OPENCV_DIR
env:
    global:
        - OPENCV_VERSION=3.2.0
        - OPENCV_DIR="$HOME/opencv-$OPENCV_VERSION"
        - LD_LIBRARY_PATH="$OPENCV_DIR/lib"
        - PKG_CONFIG_PATH="$OPENCV_DIR/lib/pkgconfig"
        - PYTHONPATH="$OPENCV_DIR/lib/python3.6/site-packages"
install:
    - sh .install-dependencies.sh
script:
    - DEBUG=TRUE xvfb-run -a python -m unittest discover
virtualenv:
    system_site_packages: true
