language: python
python:
    - "3.4"
sudo: required
dist: trusty
arch:
    packages:
        - python
        - python-numpy
        - python-matplotlib
        - python-gobject
        - python-h5py
        - python-pillow
        - python-cairocffi
        - gtksourceview3
        - opencv
        - hdf5
        - xorg-server-xvfb
    script:
        - "xvfb-run -a python3.6 -m holoview.tests.__init__"
script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
    - "./build-deb.sh"
after_success:
    - "curl -T dist/holoview-*.deb ftp://$DEPLOY_FTP_SERVER/$DEPLOY_FTP_DIRECTORY/holoview-latest.deb --user $DEPLOY_FTP_USER:'$DEPLOY_FTP_PASS'"
    - "curl -T dist/holoview-*.deb ftp://$DEPLOY_FTP_SERVER/$DEPLOY_FTP_DIRECTORY/ --user $DEPLOY_FTP_USER:'$DEPLOY_FTP_PASS'"
