language: python
python:
    - "3.4"
sudo: required
dist: trusty
arch:
    packages:
        - python
        - python-numpy
        - python-matplotlib
        - python-gobject
        - gtksourceview3
        - opencv
        - hdf5
        - python-h5py
        - xorg-server-xvfb
    script:
        - "xvfb-run -a python3.6 -m holoview.tests.__init__"
script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"


