language: python
python:
    - "3.4"
sudo: required
dist: trusty
arch:
    packages:
        - python
        - python-numpy
        - python-matplotlib
        - python-gobject
        - gtksourceview3
        - opencv
    script:
        - "python3 -c 'import cv2'"
cache:
    directories:
        - $OPENCV_DIR
env:
    global:
        - OPENCV_VERSION=3.2.0
        - OPENCV_DIR="$HOME/opencv-$OPENCV_VERSION"
        - LD_LIBRARY_PATH="$OPENCV_DIR/lib"
        - PKG_CONFIG_PATH="$OPENCV_DIR/lib/pkgconfig"
        - PYTHONPATH="$OPENCV_DIR/lib/python3.4/site-packages:/usr/lib/python3/dist-packages"
        - PYTHON="python3"
script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"


