language: python
python:
    - "3.4"
sudo: false
dist: trusty
addons:
    apt:
        packages:
            - python3-dev
            - python3-numpy
            - python3-pil
            - python3-gi
            - gir1.2-gladeui-2.0
            - gir1.2-gtk-3.0
            - libgtk2.0-dev
            - libavcodec-dev
            - libavformat-dev
            - libswscale-dev
            - libjpeg-dev
            - libpng-dev
            - libtiff-dev
            - xvfb
cache:
    directories:
        - $OPENCV_DIR
env:
    global:
        - OPENCV_VERSION=3.2.0
        - OPENCV_DIR="$HOME/opencv-$OPENCV_VERSION"
        - LD_LIBRARY_PATH="$OPENCV_DIR/lib"
        - PKG_CONFIG_PATH="$OPENCV_DIR/lib/pkgconfig"
        - PYTHONPATH="$OPENCV_DIR/lib/python3.6/site-packages:/usr/lib/python3/dist-packages"
        - PYTHON="python3.4"
install:
    - sh .install-dependencies.sh
script:
    - DEBUG=TRUE xvfb-run -a $PYTHON holoview/tests/__init__.py


