language: python
python:
    - "3.6"
sudo: required
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-opencv python3-pil python3-gi gir1.2-gladeui-2.0 python3-dev cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev python3-numpy libjpeg-dev libpng-dev libtiff-dev
cache:
    directories:
        - $OPENCV_DIR
env:
    global:
        - OPENCV_VERSION=3.2.0
        - OPENCV_DIR="$HOME/opencv-$OPENCV_VERSION"
        - LD_LIBRARY_PATH="$OPENCV_DIR/lib"
        - PKG_CONFIG_PATH="$OPENCV_DIR/lib/pkgconfig"
        - PYTHONPATH="$OPENCV_DIR/lib/python3.6/site-packages"
install:
    - ./.install_dependencies.sh
script:
    - python -m unittest discover
